### ISSUE TITLE
Http Error response when doing PostQueryAsync

### ISSUE THREAD

**Issue by vhugogarcia** [brunobrandes/api-ai-csharp#5]
Error while executing: var queryResponse = await queryAppService.PostQueryAsync(queryRequest);

`   at Api.Ai.ApplicationService.Extensions.HttpResponseMessageExtension.<ValidateResponse>d__0.MoveNext() in D:\git-projects\api-ai-csharp\src\ApplicationService\Api.Ai.ApplicationService\Extensions\HttpResponseMessageExtension.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Api.Ai.ApplicationService.Extensions.HttpResponseMessageExtension.<ToStringContentAsync>d__1.MoveNext() in D:\git-projects\api-ai-csharp\src\ApplicationService\Api.Ai.ApplicationService\Extensions\HttpResponseMessageExtension.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Api.Ai.ApplicationService.QueryAppService.<PostQueryAsync>d__2.MoveNext() in D:\git-projects\api-ai-csharp\src\ApplicationService\Api.Ai.ApplicationService\QueryAppService.cs:line 55
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Bot.Helpers.ApiAiHelper.<GetSpeechAsync>d__3.MoveNext() in C:\inetpub\wwwroot\temp\Bot\Helpers\ApiAiHelper.cs:line 81`

The code:
```
 string serviceAccessToken = UtilHelper.GetConfigKey("DialogFlowAccessToken");
                string serviceUrl = UtilHelper.GetConfigKey("DialogFlowServiceBaseUrl") + UtilHelper.GetConfigKey("DialogFlowServiceBaseApi");
                var apiAiAppServiceFactory = container.GetInstance<IApiAiAppServiceFactory>();
                var queryAppService = apiAiAppServiceFactory.CreateQueryAppService(serviceUrl, serviceAccessToken);

                var queryRequest = new QueryRequest();
                queryRequest.Lang = Language.English;
                queryRequest.Query = new string[] { msg };
                queryRequest.SessionId = "1";
```
Web.config
```
<add key="DialogFlowServiceBaseUrl" value="https://api.api.ai/" /> 
    <add key="DialogFlowServiceBaseApi" value="v1/" />
<add key="DialogFlowAccessToken" value="d732638462u2729jXXXXXX" />
```

do you have any idea why that may be happening?

**Comment by brunobrandes** [comment]
Hi @vhugogarcia 
What version of nuget are you using?
